/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author nasry
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogInBtn = new javax.swing.JButton();
        LogInBtn2 = new javax.swing.JButton();
        LogInBtn3 = new javax.swing.JButton();
        LogInBtn4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        LogInBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogInBtn.setBackground(new java.awt.Color(18, 40, 61));
        LogInBtn.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        LogInBtn.setForeground(new java.awt.Color(186, 215, 241));
        LogInBtn.setText("Cerrar sesión");
        LogInBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), null, null));
        LogInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 620, 410, 60));

        LogInBtn2.setBackground(new java.awt.Color(18, 40, 61));
        LogInBtn2.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        LogInBtn2.setForeground(new java.awt.Color(186, 215, 241));
        LogInBtn2.setText("BATTLESHIP");
        LogInBtn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), null, null));
        LogInBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(LogInBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 410, 60));

        LogInBtn3.setBackground(new java.awt.Color(18, 40, 61));
        LogInBtn3.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        LogInBtn3.setForeground(new java.awt.Color(186, 215, 241));
        LogInBtn3.setText("configuración");
        LogInBtn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), null, null));
        LogInBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(LogInBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 410, 60));

        LogInBtn4.setBackground(new java.awt.Color(18, 40, 61));
        LogInBtn4.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        LogInBtn4.setForeground(new java.awt.Color(186, 215, 241));
        LogInBtn4.setText("reportes");
        LogInBtn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), null, null));
        LogInBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(LogInBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 410, 60));

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Capture it", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 204));
        jButton2.setText("Salir");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 150, 60));

        LogInBtn1.setBackground(new java.awt.Color(18, 40, 61));
        LogInBtn1.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        LogInBtn1.setForeground(new java.awt.Color(186, 215, 241));
        LogInBtn1.setText("MI PERFIL");
        LogInBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), null, null));
        LogInBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(LogInBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 410, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MenuPrincipal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtnActionPerformed

    private void LogInBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtn2ActionPerformed

    private void LogInBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtn3ActionPerformed

    private void LogInBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtn4ActionPerformed

    private void LogInBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogInBtn;
    private javax.swing.JButton LogInBtn1;
    private javax.swing.JButton LogInBtn2;
    private javax.swing.JButton LogInBtn3;
    private javax.swing.JButton LogInBtn4;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
