/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author nasry
 */
public class PickerNave extends javax.swing.JFrame {

    /**
     * Creates new form PickerNave
     */
    public PickerNave() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogInBtn5 = new javax.swing.JButton();
        LogInBtn6 = new javax.swing.JButton();
        LogInBtn7 = new javax.swing.JButton();
        LogInBtn8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogInBtn5.setBackground(new java.awt.Color(18, 40, 61));
        LogInBtn5.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        LogInBtn5.setForeground(new java.awt.Color(186, 215, 241));
        LogInBtn5.setText("BATTLESHIP");
        LogInBtn5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), null, null));
        LogInBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(LogInBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 420, 160));

        LogInBtn6.setBackground(new java.awt.Color(18, 40, 61));
        LogInBtn6.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        LogInBtn6.setForeground(new java.awt.Color(186, 215, 241));
        LogInBtn6.setText("BATTLESHIP");
        LogInBtn6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), null, null));
        LogInBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(LogInBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 420, 160));

        LogInBtn7.setBackground(new java.awt.Color(18, 40, 61));
        LogInBtn7.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        LogInBtn7.setForeground(new java.awt.Color(186, 215, 241));
        LogInBtn7.setText("BATTLESHIP");
        LogInBtn7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), null, null));
        LogInBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(LogInBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 420, 160));

        LogInBtn8.setBackground(new java.awt.Color(18, 40, 61));
        LogInBtn8.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        LogInBtn8.setForeground(new java.awt.Color(186, 215, 241));
        LogInBtn8.setText("BATTLESHIP");
        LogInBtn8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), null, null));
        LogInBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(LogInBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 420, 160));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(26, 26, 26));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 220, 520));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserScreen.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 390, 640));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PickerBackground.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogInBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtn5ActionPerformed

    private void LogInBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtn6ActionPerformed

    private void LogInBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtn7ActionPerformed

    private void LogInBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtn8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickerNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickerNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickerNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickerNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickerNave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogInBtn5;
    private javax.swing.JButton LogInBtn6;
    private javax.swing.JButton LogInBtn7;
    private javax.swing.JButton LogInBtn8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
