/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author nasry
 */
public class PickerNave extends javax.swing.JFrame {

    /**
     * Creates new form PickerNave
     */
    public PickerNave() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogInBtn5 = new javax.swing.JButton();
        LogInBtn6 = new javax.swing.JButton();
        LogInBtn7 = new javax.swing.JButton();
        LogInBtn8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        playerName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        playerName1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        playerName2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        playerName3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        playerName4 = new javax.swing.JLabel();
        playerName5 = new javax.swing.JLabel();
        playerName6 = new javax.swing.JLabel();
        playerName7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogInBtn5.setBackground(new java.awt.Color(18, 40, 61));
        LogInBtn5.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        LogInBtn5.setForeground(new java.awt.Color(186, 215, 241));
        LogInBtn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AcorazadoBtn.png"))); // NOI18N
        LogInBtn5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), null, null));
        LogInBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(LogInBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 420, 160));

        LogInBtn6.setBackground(new java.awt.Color(18, 40, 61));
        LogInBtn6.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        LogInBtn6.setForeground(new java.awt.Color(186, 215, 241));
        LogInBtn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PortaavionesBtn.png"))); // NOI18N
        LogInBtn6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), null, null));
        LogInBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(LogInBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 420, 160));

        LogInBtn7.setBackground(new java.awt.Color(18, 40, 61));
        LogInBtn7.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        LogInBtn7.setForeground(new java.awt.Color(186, 215, 241));
        LogInBtn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SubmarinoBtn.png"))); // NOI18N
        LogInBtn7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), null, null));
        LogInBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(LogInBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 420, 160));

        LogInBtn8.setBackground(new java.awt.Color(18, 40, 61));
        LogInBtn8.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        LogInBtn8.setForeground(new java.awt.Color(186, 215, 241));
        LogInBtn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DestructorBtn.png"))); // NOI18N
        LogInBtn8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255), null, null));
        LogInBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(LogInBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 420, 160));

        jPanel1.setBackground(new java.awt.Color(200, 191, 208));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(7, 9, 73), new java.awt.Color(7, 13, 82), null, null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playerName.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        playerName.setForeground(new java.awt.Color(9, 9, 71));
        playerName.setText("PLAYER NAME");
        jPanel1.add(playerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 250, 40));

        jLabel3.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(9, 9, 71));
        jLabel3.setText("LINEUP PARA:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 40));

        jPanel2.setBackground(new java.awt.Color(200, 191, 208));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(7, 9, 73), new java.awt.Color(7, 13, 82), null, null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playerName1.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        playerName1.setForeground(new java.awt.Color(9, 9, 71));
        playerName1.setText("PLAYER NAME");
        jPanel2.add(playerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 250, 40));

        jLabel4.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(9, 9, 71));
        jLabel4.setText("LINEUP PARA:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 250, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 390, 630));

        jPanel3.setBackground(new java.awt.Color(200, 191, 208));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(7, 9, 73), new java.awt.Color(7, 13, 82), null, null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playerName2.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        playerName2.setForeground(new java.awt.Color(9, 9, 71));
        playerName2.setText("PLAYER NAME");
        jPanel3.add(playerName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 250, 40));

        jLabel5.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(9, 9, 71));
        jLabel5.setText("LINEUP PARA:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 250, 40));

        jPanel4.setBackground(new java.awt.Color(200, 191, 208));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(7, 9, 73), new java.awt.Color(7, 13, 82), null, null));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playerName3.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        playerName3.setForeground(new java.awt.Color(9, 9, 71));
        playerName3.setText("PLAYER NAME");
        jPanel4.add(playerName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 250, 40));

        jLabel6.setFont(new java.awt.Font("Capture it", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(9, 9, 71));
        jLabel6.setText("LINEUP PARA:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 250, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 390, 630));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 390, 630));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(14, 13, 42));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(229, 229, 242));
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 350, 150));

        jButton2.setText("jButton2");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 210, 70));

        jButton3.setText("jButton2");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 80, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 300, 370, 360));

        playerName4.setFont(new java.awt.Font("Capture it", 2, 36)); // NOI18N
        playerName4.setForeground(new java.awt.Color(255, 255, 255));
        playerName4.setText("portaaviones");
        getContentPane().add(playerName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 270, 40));

        playerName5.setFont(new java.awt.Font("Capture it", 2, 36)); // NOI18N
        playerName5.setForeground(new java.awt.Color(255, 255, 255));
        playerName5.setText("destructor");
        getContentPane().add(playerName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 220, 40));

        playerName6.setFont(new java.awt.Font("Capture it", 2, 36)); // NOI18N
        playerName6.setForeground(new java.awt.Color(255, 255, 255));
        playerName6.setText("submarino");
        getContentPane().add(playerName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 220, 40));

        playerName7.setFont(new java.awt.Font("Capture it", 2, 36)); // NOI18N
        playerName7.setForeground(new java.awt.Color(255, 255, 255));
        playerName7.setText("ACORAZADO");
        getContentPane().add(playerName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 220, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SelectingBackground (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogInBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtn5ActionPerformed

    private void LogInBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtn6ActionPerformed

    private void LogInBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtn7ActionPerformed

    private void LogInBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBtn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBtn8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickerNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickerNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickerNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickerNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickerNave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogInBtn5;
    private javax.swing.JButton LogInBtn6;
    private javax.swing.JButton LogInBtn7;
    private javax.swing.JButton LogInBtn8;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel playerName;
    private javax.swing.JLabel playerName1;
    private javax.swing.JLabel playerName2;
    private javax.swing.JLabel playerName3;
    private javax.swing.JLabel playerName4;
    private javax.swing.JLabel playerName5;
    private javax.swing.JLabel playerName6;
    private javax.swing.JLabel playerName7;
    // End of variables declaration//GEN-END:variables
}
